<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <RootNamespace>yandex_pract</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.4" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7"/>
    </ItemGroup>

    <ItemGroup>
        <_ContentIncludedByDefault Remove="EventServiceTest\obj\EventServiceTest.csproj.nuget.dgspec.json"/>
        <_ContentIncludedByDefault Remove="EventServiceTest\obj\project.assets.json"/>
        <_ContentIncludedByDefault Remove="EventServiceTest\obj\project.packagespec.json"/>
    </ItemGroup>

</Project>
