<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <RootNamespace>yandex_pract</RootNamespace>
        <Configurations>Debug;Release;Configuration</Configurations>
        <Platforms>AnyCPU</Platforms>
        <RootNamespace>EventsService.Web</RootNamespace>

    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
      <ProjectReference Include="..\Presentation\Presentation.csproj" />
    </ItemGroup>

</Project>
